### ISSUE TITLE
No documentation on instantiation on deployed contracts

### ISSUE THREAD

**Issue by sumukhshetty** [gnosis/gnosis.js#112]
Currently have a deployed Categorical event contract on the Ropsten network at 0x0bf128753dB586f742eaAda502301ea86a7561e6. 
How do I instantiate an object on the frontend that calls this address and has all the methods.
Generally I use web3.eth.contracts(interface,address). How do I get the access to interface on Gnosis ?

**Comment by cag** [comment]
My comment has been incorporated into the docs in #115. Hopefully, they add clarity to the usage of this library.

**Comment by sumukhshetty** [comment]
Thanks @cag 
Will continue the work. Can you tell me the specifc benefit of gnosis and what their charges are ?
I'm still not sure where I'm paying gnosis for this library. It being open source, whats my incentive to deploy it through Gnosis ?

**Comment by cag** [comment]
Do you mean what your incentive is for using what Gnosis has already deployed on the networks? If so, I would think it's just less work than deploying the contracts yourself, and in the case of mainnet, less costly, I would imagine.

At the moment, the contracts that are deployed and exposed to Gnosis JS are blind to their deployer, be it Gnosis or any other entity using the same code, so _your_ incentive as far as that goes is just reduced cost and effort (of course, you are free to verify that statement by looking at the contracts yourself, and I guess I should remark that contracts _created_ by the factories which are deployed may be aware of their creator, as in the case of the CentralizedOracle contract for example [which needs to know what account is authorized to report on an event], but not the CentralizedOracleFactory [as anybody can ask it to create a CentralizedOracle]).

As far as what your use of our free and open source library does for _us_, our hand in this is similar to other businesses which offer free or open source software. We might not benefit from you paying us directly, but we do benefit from the extra perspectives and hands working with our technology. If I may be crude: you're paying us with your time and effort using our tech. If that is disagreeable with you, you are certainly free to terminate your relationship with us, but then again, that is really the case in general with free stuff, right?

In any case, that was a business question, and we've definitely gone outside the scope of this particular issue, so I will close this thread now.
