### ISSUE TITLE
Reduce final build size

### ISSUE THREAD

**Issue by cag** [gnosis/gnosis.js#6]
Right now I got this:

```
179000 - ./~/bluebird/js/browser/bluebird.js
124000 - ./~/decimal.js/decimal.es6.js
95100 - ./~/web3/~/bignumber.js/bignumber.js
87200 - ./~/bn.js/lib/bn.js
48600 - ./~/buffer/index.js
31100 - ./~/@gnosis.pm/gnosis-core-contracts/build/contracts/EventFactory.json
29300 - ./~/crypto-js/cipher-core.js
24400 - ./~/regenerator-runtime/runtime.js
24300 - ./~/crypto-js/tripledes.js
23400 - ./~/truffle-contract/contract.js
22400 - ./~/truffle-contract-schema/~/crypto-js/core.js
22400 - ./~/crypto-js/core.js
21600 - ./~/@gnosis.pm/gnosis-core-contracts/build/contracts/StandardMarket.json
19400 - ./~/@gnosis.pm/gnosis-core-contracts/build/contracts/ScalarEvent.json
17400 - ./~/@gnosis.pm/gnosis-core-contracts/build/contracts/StandardMarketFactory.json
16700 - ./~/web3/lib/utils/utils.js
16100 - ./~/@gnosis.pm/gnosis-core-contracts/build/contracts/CategoricalEvent.json
15900 - ./~/ethjs-abi/~/js-sha3/src/sha3.js
13800 - ./~/@gnosis.pm/gnosis-core-contracts/build/contracts/UltimateOracle.json
13800 - ./~/@gnosis.pm/gnosis-core-contracts/build/contracts/Campaign.json
13700 - ./~/@gnosis.pm/gnosis-core-contracts/build/contracts/FutarchyOracle.json
13600 - ./~/@gnosis.pm/gnosis-core-contracts/build/contracts/FutarchyOracleFactory.json
13400 - ./~/crypto-js/sha512.js
12400 - ./~/ethjs-abi/lib/utils/index.js
11500 - ./~/@gnosis.pm/gnosis-core-contracts/build/contracts/CampaignFactory.json
11000 - ./~/@gnosis.pm/gnosis-core-contracts/build/contracts/Math.json
10600 - ./~/truffle-contract-schema/~/crypto-js/sha3.js
10600 - ./~/crypto-js/sha3.js
10100 - ./~/web3/lib/web3/methods/eth.js
10100 - ./~/@gnosis.pm/gnosis-core-contracts/build/contracts/UltimateOracleFactory.json
10000 - ./~/core-js/library/modules/es6.promise.js
...
```
Where number is # bytes of component.

**Comment by cag** [comment]
Strategy is to:

* replace promisification with lighter lib
* dedup bignumber/bn
* potentially remove bytecode of contracts

**Comment by collinc97** [comment]
Removing bytecode of contracts would mean users would have to compile artifacts locally right?
That includes doing the require statements within a solidity file in contracts folder?

**Comment by cag** [comment]
Well in order to make transactions, users only really need the ABI. It is possible that we won't need the bytecode. Stefan suggested going this route to reduce output size.

**Comment by cag** [comment]
Replacing promisification with custom code cut 100 kb off of minified version

**Comment by cag** [comment]
Cutting out bytecode removed another 100kB

**Comment by cag** [comment]
Oh, it is only removed for including in the JS library, which has to depend on an RPC node for making calls. I have tested it after removing the bytecode post compilation and migration and it works. In development, it should still work.

**Comment by cag** [comment]
Turns out bn.js and bignumber.js are really different libraries that have the same goal. I'm not happy with this, but this isn't something that is easily addressed, so I'm going to say it's not worth it. Final output size right now in the 300kB range...
